apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
  - urls:
    - https://github.com/jenkins-x/jx3-versions
    changes:
    - versionStream:
        kind: charts
        include:
        - cdf/*
        - jenkins-x/*
        - jx3/*
