name: Update go dependencies in jx repositories
on:
  # allow manual triggering
  workflow_dispatch: {}
  # schedule:
  # run at midnight
  # - cron: '0 0 * * *'
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      name: updatebot
      uses: docker://gcr.io/jenkinsxio/jx-updatebot:0.0.45
      with:
        args: pr -c .github/workflows/update-go/updatebot.yaml --no-version --git-credentials
